# set jekyll theme
remote_theme: jekyll/minima

# copied config settings from minima
title: Ali's Journal
author:
  name: Ali Albarosa
  email: alialbarosa@gmail.com
  
base_url: /journal
repository: albarosaali/journal

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Somewhere to keep track of life's events as they go by!

plugins:
  - jekyll-seo-tag
  - jekyll-feed
 
exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - Minima_readme.md